services:
  gateway:
    image: gateway
    build:
      context: ../
      dockerfile: ./gateway/Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      JWT_SECRET: "veryverysecretkey"
      ROOT_EMAIL: "admin@nanobank.com"
      ROOT_PASSWORD: "password"
      API_URL_AUTH: "http://auth-service:8081"
      API_URL_ACCOUNT: "http://account-service:8082"
      API_URL_TRANSACTION: "http://transaction-service:8083"
      API_URL_MAILER: "http://mailer-service:8084"
      API_URL_REDIS: "redis:6379"
    depends_on:
      - redis
      - postgres

  auth-service:
    image: auth-service
    build:
      context: ../
      dockerfile: ./auth-service/Dockerfile
    ports:
      - 8081:8080 # forward host port 8081 -> container 8080
    environment:
      PORT: "8081"
      JWT_SECRET: "veryverysecretkey"
      DNS: "postgres://user:password@postgres:5432/nanobankdb?sslmode=disable&connect_timeout=5"
      ROOT_EMAIL: "admin@nanobank.com"
      ROOT_PASSWORD: "password"
      API_URL_REDIS: "redis:6379"
    depends_on:
      - gateway

  account-service:
    image: account-service
    build:
      context: ../
      dockerfile: ./account-service/Dockerfile
    ports:
      - 8082:8080
    environment:
      PORT: "8082"
      API_URL_TRANSACTION: "http://transaction-service:8083"
      API_URL_REDIS: "redis:6379"
      DNS: "postgres://user:password@postgres:5432/nanobankdb?sslmode=disable&connect_timeout=5"
      MQ_DNS: "amqp://admin:admin@rabbitmq:5672/"
    depends_on:
      - gateway

  transaction-service:
    image: transaction-service
    build:
      context: ../
      dockerfile: ./transaction-service/Dockerfile
    ports:
      - 8083:8080
    environment:
      PORT: "8083"
      ROOT_EMAIL: "admin@nanobank.com"
      API_URL_REDIS: "redis:6379"
      DNS: "postgres://user:password@postgres:5432/nanobankdb?sslmode=disable&connect_timeout=5"
    depends_on:
      - gateway

  mailer-service:
    image: mailer-service
    build:
      context: ../
      dockerfile: ./mailer-service/Dockerfile
    ports:
      - 8084:8080
    environment:
      API_URL_MAILHOG: "mailhog:1025"
      PORT: "8084"
      MQ_DNS: "amqp://admin:admin@rabbitmq:5672/"
    depends_on:
      - gateway


  redis:
    image: docker.arvancloud.ir/redis:alpine
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web interface

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3.9-management-alpine
    ports:
      - 15672:15672 # web interface
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ../db-data/rabbitmq/:/var/lib/rabbitmq
  
  postgres:
    image: docker.arvancloud.ir/postgres:14.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nanobankdb
    volumes:
      - ../db-data/postgres/:/var/lib/postgresql/data/
      
