apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80 # cluster-wide exposed port
      targetPort: 8083 # forwards to this container port
  type: ClusterIP
