apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-authdb.sql: |-
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      username TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT now()
    );
  init-accountdb.sql: |-
    CREATE TABLE IF NOT EXISTS accounts (
      id TEXT PRIMARY KEY,
      user_id TEXT UNIQUE NOT NULL,
      username TEXT NOT NULL,
      balance BIGINT NOT NULL DEFAULT 0,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now()
    );

  init-transactiondb.sql: |-
    CREATE TYPE transaction_status AS ENUM ('pending', 'confirmed', 'canceled');

    CREATE TABLE IF NOT EXISTS transactions (
      id TEXT PRIMARY KEY,
      from_user_id TEXT NOT NULL,
      to_user_id TEXT NOT NULL,
      amount BIGINT NOT NULL,
      status transaction_status NOT NULL,
      confirmation_token UUID NOT NULL UNIQUE,
      created_at TIMESTAMP DEFAULT now(),
      updated_at TIMESTAMP DEFAULT now() 
    );

