apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80 # cluster-wide exposed port
      targetPort: 8080 # forwards to this container port
  type: NodePort 
