apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: account-service:latest # we will build this image locally
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8082 # the app will listen on this port
          env:
            - name: PORT
              value: "8082" # the env that tell the app where to listen to port
            - name: DNS
              value: "postgres://user:password@postgres:5432/nanobankdb?sslmode=disable&connect_timeout=5"
            - name: MQ_DNS
              value: "amqp://admin:admin@rabbitmq:5672/"
            - name: API_URL_REDIS
              value: "redis:6379"
            - name: API_URL_TRANSACTION
              value: "http://transaction-service:80"

