apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 80 # cluster-wide exposed port
      targetPort: 8082 # forwards to this container port
  type: ClusterIP
