apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80 # cluster-wide exposed port
      targetPort: 8081 # forwards to this container port
  type: ClusterIP
