apiVersion: v1
kind: Service
metadata:
  name: mailer-service
spec:
  selector:
    app: mailer-service
  ports:
    - protocol: TCP
      port: 80 # cluster-wide exposed port
      targetPort: 8085 # forwards to this container port
  type: ClusterIP
